### ISSUE TITLE
Download links are not .mp4 anymore

### ISSUE THREAD

**Issue by Whoelsecook** [Panopto-Video-DL/Panopto-Video-DL-browser#12]
It worked perfectly a month a ago.  

Now I am on a new lecture and failed. Please help. 

Now it will auto-download the things when I click "download" at the lower left. Separated serval files and none of them is a video format. 

The stream link ended with "hls/master.panobf2" and not a .mp4 too 
Please help~~

**Comment by pizidavi** [comment]
Hi, is not strange to have a video link not in mp4

This script was born only to get the stream link; to download the video you should use `ffmpeg`

The `.panobf2` file extension is new, it was `.m3u8` before

Try to use [ffmpeg](https://www.ffmpeg.org/download.html) and download the video with this command:

```shell
ffmpeg -f hls -i <uri> -c copy video.mp4
```

Instead of `<uri>` put the link copied from Panopto-Video-DL-browser

**Comment by Whoelsecook** [comment]
Hi, Thanks a lot for the prompt reply!! When click download, it will auto download a panobf1 file.  I use the ffmpeg to conver it to mp4.  Double time needed though but at least it works.  Thanks a lot!!

I think panopto has updated their platform.  My downloader extention can not even detect any video or m3u8 format there now.
